#!/usr/bin/env python
from __future__ import print_function

import errno
import os
import signal
import socket
import sys

sock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
# Use an available address from the abstract namespace
sock.setsockopt(socket.SOL_SOCKET, socket.SO_PASSCRED, 1)
sock.bind("")

msg = " ".join(sys.argv[1:])

try:
    sock.sendto(msg.encode("ascii"), "control")
except socket.error as e:
    if e[0] != errno.ENOENT:
        raise
    print("No control socket - did you start slowfs in this directory?")
    sys.exit(1)

payload, addr = sock.recvfrom(4096)
payload = payload.decode("ascii")
code, response = payload.split(" ", 1)
if response:
    print(response)

code = int(code, 10)
sys.exit(code)
