#!/usr/bin/env python
import errno
import os
import signal
import socket
import sys

sock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
# Use an available address from the abstract namespace
sock.setsockopt(socket.SOL_SOCKET, socket.SO_PASSCRED, 1)
sock.bind("")

msg = " ".join(sys.argv[1:])

try:
    sock.sendto(msg, "control")
except socket.error as e:
    if e[0] != errno.ENOENT:
        raise
    print "No contol socket - did you start slowfs in this directory?"
    sys.exit(1)

response, addr = sock.recvfrom(4096)

code, response = response.split(" ", 1)
if response:
    print response

code = int(code, 10)
sys.exit(code)
